# Generated by Django 3.0.2 on 2020-01-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autonumber', '0004_auto_20190602_2305'),
    ]

    operations = [
        migrations.RunSQL('''
            update autonumber_autonumber
                          set document_type=concat('invoices.', document_type)
            where document_type in (
                      'saleinvoice', 'purchaseinvoice', 'salereceipt',
                      'proformainvoice', 'advanceinvoice')

        ''', '''
            update autonumber_autonumber
                      set document_type=replace(document_type, 'invoices.', '')
        ''')
    ]
