# Generated by Django 3.0.2 on 2020-01-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190602_2305'),
        ('autonumber', '0005_doctype_names_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonumber',
            name='business_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.BusinessEntity'),
        ),
        migrations.AlterField(
            model_name='autonumber',
            name='document_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='autonumber',
            unique_together={('document_type', 'business_entity')},
        ),
    ]
