# Generated by Django 3.0.2 on 2020-01-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autonumber', '0006_auto_20200108_2052'),
    ]

    operations = [
        migrations.RunSQL(
            '''update autonumber_autonumber
                set business_entity_id = (
                    select owner_id from documents_document
                    where doctype = autonumber_autonumber.document_type limit 1
                )
            ''', '''
            update autonumber_autonumber set business_entity_id = null
            ''')
    ]
