# Generated by Django 3.0.2 on 2020-01-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190602_2305'),
        ('autonumber', '0007_update_missing_business_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonumber',
            name='business_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.BusinessEntity'),
        ),
    ]
