# Generated by Django 2.2.1 on 2019-06-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custtype',
            field=models.IntegerField(choices=[(0, 'Dostawca/Odbiorca'), (1, 'Dostawca'), (2, 'Odbiorca')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='regon',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
