# Generated by Django 3.0.2 on 2020-01-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20190602_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
    ]
