# Generated by Django 3.0.2 on 2020-01-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20190602_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pkwiu',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
