# Generated by Django 2.2.1 on 2020-01-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190602_2305'),
        ('customers', '0006_auto_20190602_2305'),
        ('documents', '0007_auto_20190603_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=64)),
                ('nip', models.CharField(blank=True, max_length=16)),
                ('regon', models.CharField(blank=True, default='', max_length=8)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('www', models.URLField(blank=True, max_length=255, null=True)),
                ('custtype', models.IntegerField(choices=[(0, 'Dostawca/Odbiorca'), (1, 'Dostawca'), (2, 'Odbiorca')])),
                ('default_manhour_price', models.PositiveIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.BusinessEntity')),
            ],
            options={
                'db_table': 'documents_customer',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentCustomer', verbose_name='Klient'),
        ),
    ]
