# Generated by Django 2.2.1 on 2020-01-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20200107_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_customer',
        ),
        migrations.AddField(
            model_name='documentcustomer',
            name='document',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document_customer', to='documents.Document'),
            preserve_default=False,
        ),
    ]
