# Generated by Django 3.0.2 on 2020-01-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20200107_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doctype',
            field=models.CharField(db_index=True, editable=False, max_length=128),
        ),
    ]
