# Generated by Django 3.0.2 on 2020-01-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20200108_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.document',),
        ),
    ]
