# Generated by Django 3.0.2 on 2020-01-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_purchasedocument_saledocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='pkwiu',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
