# Generated by Django 3.0.2 on 2020-10-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20200108_2210'),
        ('documents', '0015_auto_20200109_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='pkwiu',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='DocumentOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=64)),
                ('nip', models.CharField(max_length=16)),
                ('regon', models.CharField(max_length=8)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=64)),
                ('iban', models.CharField(max_length=33)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_owner', to='documents.Document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.BusinessEntity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
