# Generated by Django 3.0.2 on 2020-10-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20201026_0923'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentowner',
            table='documents_owner',
        ),
    ]
