# Generated by Django 3.0.2 on 2020-10-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20201026_0925'),
    ]

    operations = [
        migrations.RunSQL('''
            insert into documents_owner (
                    name, short_name, address, postal_code, city, nip,
                    regon, phone, email, bank_name, iban,
                    document_id, owner_id)
            select c.name, c.short_name, c.address, c.postal_code, c.city, c.nip,
                   c.regon, c.phone, c.email, c.bank_name, c.iban,
                    d.id, d.owner_id
            from documents_document d
            inner join userprofile_businessentity c
                on d.owner_id = c.id
        ''', '''delete from documents_owner''')
    ]
