# Generated by Django 3.0.2 on 2020-10-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_copy_owners_to_document_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='owner',
            new_name='selected_owner',
        ),
        migrations.AlterField(
            model_name='documentowner',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='documents.Document'),
        ),
    ]
