# Generated by Django 3.0.2 on 2020-10-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20200108_2210'),
        ('documents', '0019_auto_20201026_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='selected_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.BusinessEntity', verbose_name='Wybrany podmiot'),
        ),
    ]
