# Generated by Django 3.0.2 on 2020-11-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_auto_20201026_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
