# Generated by Django 3.0.2 on 2020-11-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_paid_at'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            update documents_document set paid_at = pay_date
            where paid is true and paid_at is null
            ''', '''
            update documents_document set paid_at = null
            where paid is true and paid_at = pay_date
            '''
        )
    ]
