# Generated by Django 3.0.2 on 2023-04-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20201102_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-issue_date',)},
        ),
        migrations.AddField(
            model_name='line',
            name='related_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.Line'),
        ),
    ]
