# Generated by Django 3.0.2 on 2023-04-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_auto_20230411_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='editable',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
