# Generated by Django 3.0.2 on 2023-04-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_line_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='line_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
