# Generated by Django 3.0.2 on 2023-04-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0025_line_line_number"),
    ]

    operations = [
        migrations.RunSQL(
            """
            with line_numbers as (
                select document_id, id line_id,
                    rank() over (partition by document_id order by id) new_line_number
                from documents_line
            )
            update documents_line
            set line_number = line_numbers.new_line_number
            from line_numbers
            where documents_line.id = line_numbers.line_id
        """,
            "update documents_line set line_number = 0",
        )
    ]
