# Generated by Django 4.2.25 on 2025-10-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0026_auto_20230412_0349"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="line",
            options={"ordering": ("line_number",)},
        ),
    ]
