# Generated by Django 3.0.2 on 2020-11-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
