# Generated by Django 2.2.1 on 2019-06-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.Operation'),
        ),
    ]
