# Generated by Django 2.2.1 on 2019-06-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20180604_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issuer_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Osoba wystawiająca'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Numer'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.BusinessEntity', verbose_name='Podmiot'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.Document', verbose_name='Dokument powiązany (nadrzędny)'),
        ),
        migrations.AlterField(
            model_name='line',
            name='advance_payment_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='Zaliczka brutto'),
        ),
        migrations.AlterField(
            model_name='line',
            name='advance_payment_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='Zaliczka'),
        ),
    ]
