# Generated by Django 2.2.1 on 2019-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20190602_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='pkwiu',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
