# Generated by Django 2.2.1 on 2020-01-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20200107_1107'),
    ]

    operations = [
        migrations.RunSQL('''
            insert into documents_customer (
                    name, address, postal_code, city, nip, regon, phone,
                    email, www, custtype, default_manhour_price,
                    customer_id, document_id, owner_id)
            select c.name, c.address, c.postal_code, c.city, c.nip,
                   c.regon, c.phone, c.email, c.www, c.custtype,
                   c.default_manhour_price, c.id, d.id, c.owner_id
            from documents_document d
            inner join customers_customer c
                on d.customer_id = c.id
        ''', '''delete from document_customer''')
    ]
