# Generated by Django 2.2.1 on 2020-01-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_copy_customers_to_document_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, to='customers.Customer', verbose_name='Wybrany klient'),
        ),
    ]
