# Generated by Django 2.2.1 on 2020-01-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20200107_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='customer',
            new_name='selected_customer',
        ),
        migrations.AlterField(
            model_name='documentcustomer',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='documents.Document'),
        ),
    ]
