# Generated by Django 2.2.1 on 2019-06-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0007_auto_20190602_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='unit',
            field=models.CharField(choices=[('m', 'minut'), ('h', 'godzin'), ('d', 'dni')], default='h', max_length=3),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer', verbose_name='klient'),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='date',
            field=models.DateField(verbose_name='data wyceny'),
        ),
        migrations.AlterField(
            model_name='valuationitem',
            name='max_hours',
            field=models.PositiveIntegerField(verbose_name='max godziny'),
        ),
        migrations.AlterField(
            model_name='valuationitem',
            name='min_hours',
            field=models.PositiveIntegerField(verbose_name='min godziny'),
        ),
        migrations.AlterField(
            model_name='valuationitem',
            name='name',
            field=models.CharField(max_length=128, verbose_name='opis prac / etapu'),
        ),
        migrations.AlterField(
            model_name='valuationitem',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='uwagi'),
        ),
        migrations.AlterField(
            model_name='valuationitem',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.Role', verbose_name='rola'),
        ),
        migrations.AlterField(
            model_name='valuationitem',
            name='valuation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.Valuation', verbose_name='wycena'),
        ),
    ]
