# Generated by Django 2.2.1 on 2019-06-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190602_2305'),
        ('worklog', '0008_auto_20190602_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Ticket'),
        ),
    ]
