# Generated by Django 2.2.1 on 2019-06-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0009_valuation_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationitem',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
