# Generated by Django 2.2.1 on 2019-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0010_valuationitem_proposed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='implementation_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
