# Generated by Django 2.2.1 on 2019-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0011_valuation_implementation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
