# Generated by Django 2.2.1 on 2019-06-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0012_valuation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
