# Generated by Django 2.2.1 on 2019-06-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonumber', '0003_initialize_autonumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonumber',
            name='reset_by',
            field=models.CharField(choices=[('month', 'co miesiąc'), ('year', 'co rok')], default='year', max_length=16),
        ),
    ]
