# Generated by Django 2.2.1 on 2019-06-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='acceptance',
            field=models.CharField(blank=True, choices=[('accepted', 'zaakceptowana'), ('rejected', 'odrzucona')], db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution',
            field=models.CharField(choices=[('unresolved', 'nierozwiązane'), ('cancelled', 'anulowane'), ('done', 'zakończone'), ('overpriced', 'zbyt wysoki koszt'), ('nobudget', 'brak środków na realizację')], db_index=True, default='unresolved', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'nowe'), ('pricing', 'wycena'), ('queued', 'przyjęte do realizacji'), ('inprogress', 'w toku'), ('rejected', 'oferta odrzucona'), ('closed', 'zamknięte')], db_index=True, default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('order', 'zapotrzebowanie'), ('warranty', 'reklamacja'), ('issue', 'problem')], db_index=True, max_length=16),
        ),
    ]
