# Generated by Django 2.2.1 on 2019-06-02 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20190602_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='roles',
            field=models.ManyToManyField(through='userprofile.AssociateRoleCosts', to='userprofile.Role', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='konto'),
        ),
        migrations.AlterField(
            model_name='associaterolecosts',
            name='manhour_cost',
            field=models.PositiveIntegerField(verbose_name='koszt roboczogodziny'),
        ),
        migrations.AlterField(
            model_name='associaterolecosts',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Role', verbose_name='rola'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nazwa'),
        ),
    ]
