# Generated by Django 3.0.2 on 2020-01-08 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0005_auto_20190602_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentity',
            name='employers',
            field=models.ManyToManyField(blank=True, null=True, related_name='works_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_entity', to=settings.AUTH_USER_MODEL),
        ),
    ]
