# Generated by Django 4.2.25 on 2025-10-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_operation_internal"),
        ("userprofile", "0006_auto_20200108_2210"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessentity",
            name="default_cash_payment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="payments.paymenttype",
            ),
        ),
        migrations.AddField(
            model_name="businessentity",
            name="default_transfer_payment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="payments.paymenttype",
            ),
        ),
    ]
